apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/<your-username>/nginx-k8s.git
    targetRevision: main
    path: base
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

